### ISSUE TITLE
Map Pool suggestions (OLD OC additions)

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/overcastcommunity.github.io#28]
I was browsing through the old OC maps on the resourcepile na found what I though were 2 iconic maps that deserved to be in PGM. The first map is SuperPrism and maybe it's variants (classic). The map was a fun FFA map which made great use of the boost panels. Images attached below

The second map is WildWood crevice which was a fun FFA. It looked and played really nicely too... which I used to love back in the day.

I have checked and none of these maps exist on the server or in any pools so I was wondering if these classics could be added in. 

my discord is Technodono#2139 and I am a part of the PMG server if you need further contact

![2020-08-07_17 17 23](https://user-images.githubusercontent.com/22761234/89642735-b39aa680-d8f7-11ea-8210-bffc6686e2e6.png)

**Comment by Brottweiler** [comment]
This is totally the wrong repo to suggest something like this. A more appropriate repo would be https://github.com/OvercastCommunity/MapPools, but even then #feedback on discord might be better.
