### ISSUE TITLE
Where to find image assets?

### ISSUE THREAD

**Issue by drmzio** [OvercastCommunity/overcastcommunity.github.io#37]
Specifically looking for the oc.tc logo in vector format if it even exists? I'm thinking about a potential business idea for oc.tc to introduce a merch store and have some sick oc.tc designs (just an idea). Possibly have an incentive to purchase the merch by offering a 1 month "donor" badge in game? What do you think?

**Comment by Brottweiler** [comment]
The highest resolution image of the logo is 512x PNG. 

Merch store is definitely an option and there are services that provide custom merch. If we want to look into that we'll. Thank you. :)
