### ISSUE TITLE
Detect dark mode using css

### ISSUE THREAD

**Issue by Brottweiler** [OvercastCommunity/overcastcommunity.github.io#7]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by ChemistryX** [comment]
Does current method have any problem?

**Comment by Brottweiler** [comment]
Page shows in light mode at refresh before JavaScript loads dark mode. This is especially noticably even not cached. Would be better to about js and only use css if possible.
