### ISSUE TITLE
Verify OvercastCommunity's control over oc.tc domain

### ISSUE THREAD

**Issue by TheRealPear** [OvercastCommunity/overcastcommunity.github.io#91]
Opening this as an issue ticket under this repository since it's relevant, but not quite related to the website's source files. Whoever owns the OvercastCommunity organization would need to add the [`oc.tc` domain as a verified domain](https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization) so GitHub can display the badge where it displays that it is managed by this organization.

The [PGMDev organization](https://github.com/PGMDev) already utilizes this and I think it would be a nice addition. Similarly, the [old OvercastNetwork organization](https://github.com/OvercastNetwork) doesn't have any domain listed, so I'm not sure if this would cause any conflict.
![A screenshot of the PGMDev GitHub organization with its green Verified badge](https://github.com/OvercastCommunity/overcastcommunity.github.io/assets/20259871/942ffb03-2f19-47b1-ac7d-af8f88db6b05)

**Comment by Brottweiler** [comment]
Done!
